<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => 'Velvet Armchair',
                'description' => 'A luxurious velvet armchair with a plush design and elegant golden legs.',
                'price' => 120.00,
                'sales_count' => 15,
                'category_id' => 1,
                'weight' => '2 lbs',
                'dimensions' => '12 × 16 × 19 in',
                'color' => 'Gray, Black',
                'size' => 'S, M, L, XL',
                'model' => 'VA2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Wipe with a damp cloth.',
                'brand' => 'Luxury Home',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>1,
            ],
            [
                'name' => 'Chair Pillow',
                'description' => 'A soft and supportive chair pillow made with high-quality fabric.',
                'price' => 15.00,
                'sales_count' => 10,
                'category_id' => 1,
                'weight' => '1 kg',
                'dimensions' => '45 x 45 cm',
                'color' => 'Gray',
                'size' => 'Standard',
                'model' => 'CP2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Machine wash on gentle cycle.',
                'brand' => 'Comfort Plus',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>10,
            ],
            [
                'name' => 'Dining Arm Chair',
                'description' => 'A stylish dining armchair made of solid wood and upholstered fabric.',
                'price' => 85.00,
                'sales_count' => 8,
                'category_id' => 1,
                'weight' => '10 kg',
                'dimensions' => '55 x 55 x 85 cm',
                'color' => 'Brown',
                'size' => 'Large',
                'model' => 'DAC2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Wipe with a dry cloth.',
                'brand' => 'HomeCraft',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' => null,
            ],
            [
                'name' => 'Leather Chair',
                'description' => 'A sleek leather-upholstered chair with ergonomic design.',
                'price' => 140.00,
                'sales_count' => 7,
                'category_id' => 1,
                'weight' => '12 kg',
                'dimensions' => '60 x 60 x 95 cm',
                'color' => 'Black',
                'size' => 'Medium',
                'model' => 'LC2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Clean with a damp cloth.',
                'brand' => 'Elite Leather',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>9,

            ],
            [
                'name' => 'Swivel Dining Armchair',
                'description' => 'An ergonomic dining chair with a swivel function.',
                'price' => 110.00,
                'sales_count' => 6,
                'category_id' => 1,
                'weight' => '12 kg',
                'dimensions' => '60 x 60 x 95 cm',
                'color' => 'Gray',
                'size' => 'Medium',
                'model' => 'SDA2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Clean with a soft cloth.',
                'brand' => 'Elegant Living',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>8,
            ],
            [
                'name' => 'Artisan Neva Chair',
                'description' => 'Handcrafted artisan chair made from high-quality wood.',
                'price' => 95.00,
                'sales_count' => 20,
                'category_id' => 2,
                'weight' => '10 kg',
                'dimensions' => '55 x 60 x 90 cm',
                'color' => 'Wooden',
                'size' => 'Medium',
                'model' => 'ANC2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Wipe with a soft cloth.',
                'brand' => 'Artisan Woodworks',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' => null,
            ],
            [
                'name' => 'Dining Arm Chair Outdoor',
                'description' => 'Durable outdoor chair designed for your patio or garden.',
                'price' => 75.00,
                'sales_count' => 0,
                'category_id' => 2,
                'weight' => '8 kg',
                'dimensions' => '60 x 60 x 85 cm',
                'color' => 'Beige',
                'size' => 'Large',
                'model' => 'DACO2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Clean with mild soap and water.',
                'brand' => 'Outdoor Comfort',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>7,
            ],
            [
                'name' => 'Accent Chairs',
                'description' => 'Elegant accent chairs to add charm to any space.',
                'price' => 69.00,
                'sales_count' => 0,
                'category_id' => 2,
                'weight' => '12 kg',
                'dimensions' => '55 x 60 x 90 cm',
                'color' => 'Red',
                'size' => 'Medium',
                'model' => 'AC2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Vacuum regularly.',
                'brand' => 'Decor Living',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' => null,
            ],
            [
                'name' => 'Dining Table',
                'description' => 'A solid wood dining table perfect for gatherings.',
                'price' => 160.00,
                'sales_count' => 0,
                'category_id' => 1,
                'weight' => '30 kg',
                'dimensions' => '160 x 90 x 75 cm',
                'color' => 'Wooden',
                'size' => 'Large',
                'model' => 'DT2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Use coasters to avoid scratches.',
                'brand' => 'Classic Woodworks',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>6,
            ],
            [
                'name' => 'Modular Sectional Sofa - L Shape Couch',
                'description' => 'L-shaped modular sofa designed for modern living.',
                'price' => 420.00,
                'sales_count' => 0,
                'category_id' => 1,
                'weight' => '45 kg',
                'dimensions' => '250 x 100 x 85 cm',
                'color' => 'Gray',
                'size' => 'Large',
                'model' => 'MSS2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Spot clean with a fabric cleaner.',
                'brand' => 'Modern Comfort',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' => null,
            ],
            [
                'name' => 'Modern Sofa',
                'description' => 'Stylish 3-seater sofa with durable fabric.',
                'price' => 350.00,
                'sales_count' => 0,
                'category_id' => 1,
                'weight' => '35 kg',
                'dimensions' => '220 x 85 x 90 cm',
                'color' => 'Beige',
                'size' => 'Medium',
                'model' => 'MSO2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Use fabric cleaner.',
                'brand' => 'Comfort Living',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>5,
            ],
            [
                'name' => 'Wooden Bed Frame',
                'description' => 'A modern wooden bed frame with a strong build.',
                'price' => 270.00,
                'sales_count' => 0,
                'category_id' => 2,
                'weight' => '50 kg',
                'dimensions' => '200 x 150 x 40 cm',
                'color' => 'Brown',
                'size' => 'King',
                'model' => 'WBF2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Wipe with damp cloth.',
                'brand' => 'Classic Comfort',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' => null,
            ],
            [
                'name' => 'Rocking Chair',
                'description' => 'Wooden rocking chair for comfort and relaxation.',
                'price' => 90.00,
                'sales_count' => 0,
                'category_id' => 1,
                'weight' => '15 kg',
                'dimensions' => '65 x 55 x 100 cm',
                'color' => 'Oak',
                'size' => 'Medium',
                'model' => 'RC2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Do not expose to moisture.',
                'brand' => 'Rocking Comfort',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>4,
            ],
            [
                'name' => 'Full Length Mirror',
                'description' => 'A full-length mirror suitable for dressing and decor.',
                'price' => 35.00,
                'sales_count' => 0,
                'category_id' => 2,
                'weight' => '8 kg',
                'dimensions' => '180 x 60 cm',
                'color' => 'Silver',
                'size' => 'Large',
                'model' => 'FLM2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Wipe with a soft cloth.',
                'brand' => 'Elegant Mirrors',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' => null,
            ],
            [
                'name' => 'DEWFIG Arched Full Length Mirror',
                'description' => 'A sleek full-length mirror with a gold frame.',
                'price' => 30.00,
                'sales_count' => 0,
                'category_id' => 2,
                'weight' => '6 kg',
                'dimensions' => '160 x 50 cm',
                'color' => 'Gold',
                'size' => 'Medium',
                'model' => 'DFLFM2023',
                'shipping' => 'Free shipping within Jordan.',
                'care_info' => 'Wipe with soft cloth.',
                'brand' => 'DEWFIG',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>3,
            ],
            [
                'name' => 'Luxurious Modern Bed with Gold Accents',
                'description' => 'A queen‑size modern bed upholstered in plush velvet, featuring gold‑plated trim on the tufted headboard and footboard. Solid hardwood frame with reinforced slats for superior support and a sleek, glamorous look.',
                'price' => 27.99,
                'sales_count' => 0,
                'category_id' => 2,
                'weight' => '70 kg',
                'dimensions' => '200 x 160 x 40 cm',
                'color' => 'Velvet Black',
                'size' => 'Queen',
                'model' => 'LMBG2023',
                'shipping' => 'Free shipping within Jordan. Delivery within 5-7 business days.',
                'care_info' => 'Vacuum regularly. Wipe stains with a damp cloth.',
                'brand' => 'Luxura',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' => null,
            ],
            [
                'name' => 'Light Luxury Bedside Table',
                'description' => 'A contemporary bedside table crafted from light ash wood with a matte finish, featuring a single soft‑close drawer with gold‑plated handle and slender tapered legs for a refined, airy look.',
                'price' => 49.99,
                'sales_count' => 0,
                'category_id' => 2,
                'weight' => '15 kg',
                'dimensions' => '50 x 40 x 60 cm',
                'color' => 'Light Ash',
                'size' => 'Medium',
                'model' => 'LLBT2023',
                'shipping' => 'Free shipping within Jordan. Delivery within 5-7 business days.',
                'care_info' => 'Wipe with a soft, damp cloth.',
                'brand' => 'Elegance Living',
                'created_at' => now(),
                'updated_at' => now(),
                'discount_id' =>2,
            ],
        ]);
    }
}
